# Generated by Django 5.2.6 on 2025-11-09 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='Visit_Fee',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
