# Generated by Django 5.2.6 on 2025-11-09 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_visit_fee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='Visit_Fee',
            new_name='visit_Fee',
        ),
    ]
