# Generated by Django 5.2.6 on 2025-11-09 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_doctornotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='specialization',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
