# Generated by Django 5.2.6 on 2025-11-09 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_alter_doctorprofile_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='Visit_Fee',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
