# Generated by Django 5.2.6 on 2025-11-09 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0005_doctorprofile_visit_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='highest_qualification',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
