# Generated by Django 5.2.6 on 2025-11-09 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0006_alter_doctorprofile_highest_qualification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorprofile',
            old_name='Visit_Fee',
            new_name='visit_Fee',
        ),
    ]
