# Generated by Django 5.2.6 on 2025-11-09 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0007_rename_visit_fee_doctorprofile_visit_fee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorprofile',
            old_name='visit_Fee',
            new_name='visit_fee',
        ),
    ]
